name: First Workflow

on:
   push:
     branches:
       - main

jobs: 
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "Welcome to our first GitHub Actions Workflow!"

      - name: checkout repo
        uses: actions/checkout@v5.0.0

      - name: listing repo files
        run: ls -la

