on:
  push:
    branches:
      - main
      - "release/*"
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
      - "release/*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests
        run: cd src && npm test